import {autoGeneratedRoutesListMap} from "../../Router/routesList";

export const customBreadCrumbsNameMap = new Map([
    ...autoGeneratedRoutesListMap,
    ['customization', 'Настройки'],
    ['tutors', 'Репетиторы'],
    ['universities', 'ВУЗЫ'],
    ['colleges', 'ССУЗЫ'],
    ['tests', 'Тесты']
])