import {ReactNode} from "react";
import QueryStatsIcon from '@mui/icons-material/QueryStats';
import SettingsIcon from '@mui/icons-material/Settings';
import SchoolOutlinedIcon from '@mui/icons-material/SchoolOutlined';
import QuizIcon from '@mui/icons-material/Quiz';
import PersonIcon from '@mui/icons-material/Person';
import {TutorsTablePage} from "../pages/TutorsTablePage/TutorsTablePage";

export interface IRoute {
    path: string,
    name: string
    component: ReactNode
    icon?: ReactNode
    routes?: IRoute[]
}


export const routesList: IRoute[] = [
    {path: '/', name: 'Статистика', icon: <QueryStatsIcon/>, component: null},

    // {path:'/tutors', name:'Репетиторы', component:<p>xyz</p>},
    //
    // {path:'/universities', name:'ВУЗЫ', component:null},
    //
    // {path:'/colleges', name:'ССУЗЫ', component:null},
    //
    // {path:'/tests', name:'Тесты', component:null},

    {
        path: 'customization', name: 'Настройки', icon: <SettingsIcon/>, component: null,
        routes: [
            {path: 'tutors', name: 'Настройка репетиторов', icon: <PersonIcon/>, component: <TutorsTablePage/>},

            {path: 'universities', name: 'Настройка ВУЗОВ', icon: <SchoolOutlinedIcon/>, component: null},

            {path: 'colleges', name: 'Настройка ССУЗОВ', icon: <SchoolOutlinedIcon/>, component: null},

            {path: 'tests', name: 'Настройка тестов', icon: <QuizIcon/>, component: null}
        ]
    },
]

const mapRoutesList = (routesList: IRoute[]): [string, string][] => {
    const resultArr: [string, string][] = []

    routesList.map((item) => {
        resultArr.push([item.path, item.name])
        if (item.routes) {
            resultArr.push(...mapRoutesList(item.routes))
        }
    })

    return resultArr
}
export const autoGeneratedRoutesListMap = new Map(mapRoutesList(routesList))