import {ReactNode} from "react";
import {TutorsTablePage} from "../pages/TutorsTablePage/TutorsTablePage";
import {UniversitiesTablePage} from "../pages/UniversitiesTablePage/UniversitiesTablePage";

export interface IRoute {
    path: string,
    name: string
    component: ReactNode
    routes?: IRoute[]
}


export const routesList: IRoute[] = [
    {path: '/', name: 'Статистика', component: null},

    // {path:'/tutors', name:'Репетиторы', component:<p>xyz</p>},
    //
    // {path:'/universities', name:'ВУЗЫ', component:null},
    //
    // {path:'/colleges', name:'ССУЗЫ', component:null},
    //
    // {path:'/tests', name:'Тесты', component:null},

    {path: 'customization/tutors', name: 'Настройка репетиторов', component: <TutorsTablePage/>},

    {path: 'customization/universities', name: 'Настройка ВУЗОВ', component:<UniversitiesTablePage/>},
    {path: 'customization/universities/view', name: 'ВУЗ', component:null},
    {path: 'customization/universities/edit', name: 'Настройка ВУЗА', component:null},
    {path: 'customization/universities/new', name: 'Создание ВУЗА', component:null},

    {path: 'customization/colleges', name: 'Настройка ССУЗОВ', component: null},

    {path: 'customization/tests', name: 'Настройка тестов', component: null}
]

const mapRoutesList = (routesList: IRoute[]): [string, string][] => {
    const resultArr: [string, string][] = []

    routesList.map((item) => {
        resultArr.push([item.path, item.name])
        if (item.routes) {
            resultArr.push(...mapRoutesList(item.routes))
        }
    })

    return resultArr
}
export const autoGeneratedRoutesListMap = new Map(mapRoutesList(routesList))